<?php

/**
 * Client
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xxi
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{
  public function getOrdersByState($state, $viewOnlyMine=true)
  {
    $query = Doctrine_Core::getTable('Order')->createQuery('a')
      ->orderBy('created_at')
    ;

    if ($viewOnlyMine) {
      $query
        ->andWhere('a.created_by = ?', sfContext::getInstance()->getUser()->getGuardUser()->getId())
      ;
    }

    $query
      ->andWhere('a.client_id = ?', $this->getId())
    ;

    switch ($state) {
      case 'active':
        $query
          ->andWhereNotIn('a.state', array(
            'archived',
            'debt',
          ))
        ;
      break;

      default:
        $query
          ->andWhere('a.state = ?', $state)
        ;
      break;
    }

    return $query
      ->execute()
    ;
  }

  public function getOwnershipTranslated()
  {
    return true == ($ownership=$this->_get('ownership'))
      ? ClientTable::$ownership[ $ownership ]
      : ''
    ;
  }

  public function getNameWithDiscount()
  {
    return $this->getName() . '|' . (int)$this->getDiscount();
  }
}
