<?php

/**
 * Client
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xxi
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{
  public function getOrdersByState($state)
  {
    return Doctrine_Core::getTable('Order')->createQuery('a')
      ->where('a.created_by = ?', $this->getId())
      ->andWhere('a.state '
        . ($state == 'active' ? '!=' : '=') . ' ?',
        ($state == 'active' ? 'archived' : $state)
      )
      ->execute()
    ;
  }
}
