<?php

/**
 * CommentReadsTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentReadsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentReadsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommentReads');
    }
}
