<?php

/**
 * Comment
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xxi
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comment extends BaseComment
{
    public function getReadAndMarkAsRead()
    {
        if (!$this->_get('read')) {
            // we need raw query because of `inser ignore'
            $this->_table->getConnection()->exec("
        INSERT IGNORE INTO
        `comment_reads`
        (
          `id`,
          `comment_id`,
          `user_id`
        ) VALUES (
          NULL,
          '" . $this->getId() . "',
          '" . sfContext::getInstance()->getUser()->getGuardUser()->getId() . "'
        );"
            );
        }

        return $this->_get('read');
    }
}
