<?php

/**
 * CompamySettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompamySettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompamySettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompamySettings');
    }
}