<?php

/**
 * ContractorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContractorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContractorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contractor');
    }
}