<?php

/**
 * Invoice
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xxi
 * @subpackage model
 * @author     Saritskiy Roman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invoice extends BaseInvoice
{
    private function autoSum($event)
    {
        $invoice = $event->getInvoker();

        $sum = $invoice->getNumber() * $invoice->getPrice();
        $invoice->setSum(round($sum, 2));
    }

    public function preInsert($event)
    {
        $this->autoSum($event);
    }

    public function preUpdate($event)
    {
        $this->autoSum($event);
    }
}
