<?php

/**
 * Material
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xxi
 * @subpackage model
 * @author     Saritskiy Roman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Material extends BaseMaterial
{
  protected $arrivalsAmount = null;
  protected $utilizationsAmount = null;

  public function getNameWithDimension()
  {
    return $this->getName() . ', ' . $this->getDimension();
  }

  public function getArrivalsAmount()
  {
    if (null === $this->arrivalsAmount) {
      $this->arrivalsAmount = (double)Doctrine_Query::create()
        ->from('Arrival a')
        ->select('sum(a.amount)')
        ->addWhere('a.material_id = ?', $this->getId())
        ->execute([], Doctrine_Core::HYDRATE_SINGLE_SCALAR)
      ;
    }

    return $this->arrivalsAmount;
  }

  public function getUtilizationsAmount()
  {
    if (null === $this->utilizationsAmount) {
      $this->utilizationsAmount = (double)Doctrine_Query::create()
        ->from('Utilization u')
        ->select('sum(u.amount)')
        ->addWhere('u.material_id = ?', $this->getId())
        ->execute([], Doctrine_Core::HYDRATE_SINGLE_SCALAR)
      ;
    }

    return $this->utilizationsAmount;
  }

  public function getRemainedAmount()
  {
    return $this->getArrivalsAmount() - $this->getUtilizationsAmount();
  }
}
