<?php

/**
 * MaterialMovementUtilizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialMovementUtilizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialMovementUtilizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialMovementUtilization');
    }
}