<?php

/**
 * MaterialMovementMaterialsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialMovementMaterialsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialMovementMaterialsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialMovementMaterials');
    }
}