<?php

/**
 * MaterialMovementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialMovementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialMovementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialMovement');
    }
}