<?php

/**
 * MaterialMovementWriteoffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialMovementWriteoffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialMovementWriteoffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialMovementWriteoff');
    }
}