<?php

/**
 * Material
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xxi
 * @subpackage model
 * @author     Saritskiy Roman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Material extends BaseMaterial
{
  public function getNameWithDimension()
  {
    return $this->getName() . ', ' . $this->getDimension();
  }

  public function getArrivalsAmount()
  {
    return (double)Doctrine_Query::create()
      ->from('Arrival a')
      ->select('count(a.amount)')
      ->addWhere('a.material_id = ?', $this->getId())
      ->execute([], Doctrine_Core::HYDRATE_SINGLE_SCALAR)
    ;
  }

  public function getUtilizationsAmount()
  {
    return (double)Doctrine_Query::create()
      ->from('Utilization u')
      ->select('count(u.amount)')
      ->addWhere('u.material_id = ?', $this->getId())
      ->execute([], Doctrine_Core::HYDRATE_SINGLE_SCALAR)
    ;
  }
}
