<?php

/**
 * MaterialMovement
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xxi
 * @subpackage model
 * @author     Saritskiy Roman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MaterialMovement extends BaseMaterialMovement
{
    public function getTypeTranslated()
    {
        $types = [
            "arrival" => "Приход",
            "transfer" => "Перемещение",
            "utilization" => "Расход",
            "writeoff" => "Списание",
        ];

        return isset($types[$this->getType()]) ? $types[$this->getType()] : $this->getType();
    }
}
