<?php

/**
 * MaterialMovementTransferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialMovementTransferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialMovementTransferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialMovementTransfer');
    }
}