<?php

/**
 * MaterialMovementArrivalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialMovementArrivalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialMovementArrivalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialMovementArrival');
    }
}