<?php

/**
 * OrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderTable extends Doctrine_Table
{
    public static $states = array(
      'calculating' => 'На просчёте',
      'work' => 'В цех',
      'working' => 'В работе',
      'done' => 'Всё готово',
      'submited' => 'Сдан',
      'archived' => 'В архиве',
      'debt' => 'Дебиторка'
    );

    /**
     * Returns an instance of this class.
     *
     * @return object OrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Order');
    }
}