<?php

/**
 * OrdersTableFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdersTableFilterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdersTableFilterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdersTableFilter');
    }
}