<?php

/**
 * OrdersTableSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdersTableSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdersTableSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdersTableSettings');
    }
}