<?php

/**
 * Order
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xxi
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order extends BaseOrder
{
  public function getStateTranslated()
  {
    return OrderTable::$states[ $this->_get('state') ];
  }

  public function getColorIndicator()
  {
    $colors = array(
      'calculating' => '',
      'work' => 'alert-error',
      'working' => 'alert',
      'done' => 'alert-success',
      'submited' => '',
      'archived' => '',
      'debt' => ''
    );

    return $colors[ $this->getState() ];
  }
}
