<?php

/**
 * OrderVersionableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderVersionableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderVersionableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderVersionable');
    }
}