<?php

/**
 * OrderTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderTable extends Doctrine_Table
{
  public static $states = array(
    "calculating" => "На просчёте",
    "prepress" => "Дизайн (препресс)",
    "work" => "В цех",
    "working" => "В работе",
    "done" => "Всё готово",
    "submited" => "Сдан",
    "archived" => "В архиве",
    "debt" => "Дебиторка",
    "deleted" => "Удалён",
  );

  public static function getSetableStates()
  {
    $user = sfContext::getInstance()->getUser();

    $statesForManager = array(
      "calculating",
      "work",
      "prepress",
    );
    $statesForWorker = array(
      "calculating",
      "work",
      "working",
      "done",
      "submited",
      "prepress",
    );
    $statesForMaster = array(
      "working",
      "done",
    );
    $statesForMonitor = array(
      "work",
      "working",
      "done",
    );
    $statesForBuhgalter = array(
      "archived",
      "debt",
    );

    return array_unique(array_merge(
      []
      , $user->hasCredential("manager") ? $statesForManager : []
      , $user->hasCredential("worker") ? $statesForWorker : []
      , $user->hasCredential("master") ? $statesForMaster : []
      , $user->hasCredential("monitor") ? $statesForMonitor : []
      , $user->hasCredential("buhgalter") ? $statesForBuhgalter : []
      , $user->hasCredential("can-delete-orders") ? ["deleted"] : []
    ));
  }

  public static function getSetableStatesWithNames()
  {
    return array_intersect_key(self::$states, array_flip(self::getSetableStates()));
  }

  public static $payMethods = array(
    "" => "",
    "cash" => "Наличный",
    "non-cash" => "Безналичный",
    "barter" => "Бартер",
    "settlement" => "Взаиморасчёт",
  );

  public static $area = array(
    "" => "",
    "pvc" => "PVC",
    "laser" => "ЛАЗЕР",
    "engraver" => "ГРАВЕР",
    "mymaka" => "МИМАКА",
    "outdoor" => "НАРУЖНАЯ РЕКЛАМА",
    "lfp" => "ПЕЧАТЬ ШФП",
    "sublimation" => "СУБЛИМАЦИЯ",
    "cutter" => "ФРЕЗЕР",
    "serigraphy" => "ШЕЛКОГРАФИЯ",
  );

  /**
   * Returns an instance of this class.
   *
   * @return object OrderTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable("Order");
  }
}
