<?php

/**
 * Pay
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xxi
 * @subpackage model
 * @author     Saritskiy Roman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Pay extends BasePay
{
  public function preInsert($event)
  {
    $pay = $event->getInvoker();
    $order = $pay->getOrder();

    $payedSum = Doctrine_Query::create()
      ->select('sum(p.amount) as payedSum')
      ->from('Pay p')
      ->addWhere('p.order_id = ?', $pay->getOrderId())
      ->execute([], Doctrine_Core::HYDRATE_SINGLE_SCALAR)
    ;

    if ($payedSum >= $order->getCost()) {
      $order
        ->setPayedAt($pay->getPayedAt())
        ->save()
      ;
    }
  }
}
