<?php

/**
 * PayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pay');
    }
}