<?php

/**
 * RefAreaUserTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefAreaUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefAreaUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefAreaUser');
    }
}
