<?php

/**
 * RefAreaWorkerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefAreaWorkerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefAreaWorkerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefAreaWorker');
    }
}