<?php

/**
 * RefOrderWorkTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefOrderWorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefOrderWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefOrderWork');
    }
}
