<?php

/**
 * RefOrderWork
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xxi
 * @subpackage model
 * @author     Saritskiy Roman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefOrderWork extends BaseRefOrderWork
{
    public function getPlannedAt()
    {
        return $this->getPlannedStart() || $this->getPlannedFinish()
            ? date('d.m.Y H:i', strtotime($this->getPlannedStart())) . '—' . date('d.m.Y H:i',
                strtotime($this->getPlannedFinish()))
            : 'не запланировано';
    }
}
