<?php

/**
 * RefSupplierMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefSupplierMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefSupplierMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefSupplierMaterial');
    }
}