<?php

/**
 * RefUtilizationArrivalTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefUtilizationArrivalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefUtilizationArrivalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefUtilizationArrival');
    }
}
