<?php

/**
 * RefWarehouseUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefWarehouseUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefWarehouseUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefWarehouseUser');
    }
}