<?php

/**
 * Utilization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    xxi
 * @subpackage model
 * @author     Saritskiy Roman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Utilization extends BaseUtilization
{
  public function preSave($event)
  {
    $utilization = $event->getInvoker();
    $changes = $utilization->getModified(true);

    if ($changes['amount']) {
      if ($changes['amount'] < $utilization->getAmount()) { // more utilized
        // add some RefUtilizationArrival
      } else { // less utilized
        // remove some RefUtilizationArrival
      }
    }
  }
}
