<?php

/**
 * UtilizationPlanTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtilizationPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtilizationPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtilizationPlan');
    }
}
