<?php

/**
 * UtilizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtilizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtilizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Utilization');
    }
}