new:
  credentials: [[manager, director]]

create:
  credentials: [[manager, director]]

edit:
  credentials: [[manager, worker, buhgalter, director]]

update:
  credentials: [[manager, worker, buhgalter, director]]

show:
  credentials: [[manager, worker, director, buhgalter, monitor]]
