new:
  credentials: [manager]

create:
  credentials: [manager]

edit:
  credentials: [[manager, worker, buhgalter]]

update:
  credentials: [[manager, worker, buhgalter]]

show:
  credentials: [[manager, worker, director, buhgalter]]
