new:
  credentials: [[manager, director]]

create:
  credentials: [[manager, director]]

edit:
  credentials: [[manager, worker, buhgalter, director, master]]

update:
  credentials: [[manager, worker, buhgalter, director, master]]

show:
  credentials: [[manager, worker, director, buhgalter, monitor, master]]
