new:
  credentials: [[manager, director]]

create:
  credentials: [[manager, director]]

edit:
  credentials: [[manager, worker, buhgalter, director, master, design-worker]]

update:
  credentials: [[manager, worker, buhgalter, director, master, design-worker]]

show:
  credentials: [[manager, worker, director, buhgalter, monitor, master, design-worker, design-master]]
