# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: main, action: index }

company-settings:
  url:   /company-settings/:id
  param: { module: comsettings, action: show }

share-settings:
  url:   /share-settings/:id
  param: { module: sharesettings, action: show}

invoice:
  url:   /invoice
  param: { module: order, action:invoice }

clients:
  url:   /clients
  param: { module: client, action: index }

client:
  url:   /clients/:id/:state
  param: { module: client, action: show, state: active }
  requirements:
    id: \d+
    state: <?php echo join('|', array_keys(OrderTable::$states)) ?>

client-new:
  url:   /clients/new
  param: { module: client, action: new }

client-create:
  url:   /clients/create
  param: { module: client, action: create }

client-edit:
  url:   /clients/:id/edit
  param: { module: client, action: edit }
  requirements: { id: \d+ }

client-update:
  url:   /clients/:id/update
  param: { module: client, action: update }
  requirements: { id: \d+ }

client-del:
  url:   /clients/:id/del
  param: { module: client, action: del }
  requirements: { id: \d+ }

suppliers:
  url:   /suppliers
  param: { module: supplier, action: index }

supplier:
  url:   /suppliers/:id
  param: { module: supplier, action: show }
  requirements:
    id: \d+

supplier-new:
  url:   /suppliers/new
  param: { module: supplier, action: new }

supplier-create:
  url:   /suppliers/create
  param: { module: supplier, action: create }

supplier-edit:
  url:   /suppliers/:id/edit
  param: { module: supplier, action: edit }
  requirements: { id: \d+ }

supplier-update:
  url:   /suppliers/:id/update
  param: { module: supplier, action: update }
  requirements: { id: \d+ }

supplier-del:
  url:   /clients/:id/del
  param: { suppliers: supplier, action: del }
  requirements: { id: \d+ }

orders:
  url:   /orders/:my/:state
  param: { module: order, action: index, state: active, my: all }
  requirements:
    my: my|all
    state: <?php echo join('|', array_keys(OrderTable::$states)) ?>

order:
  url:   /orders/:id
  param: { module: order, action: show }
  requirements: { id: \d+ }

order-new:
  url:   /orders/new
  param: { module: order, action: new }

order-create:
  url:   /orders/create
  param: { module: order, action: create }

order-edit:
  url:   /orders/:id/edit
  param: { module: order, action: edit }
  requirements: { id: \d+ }

order-update:
  url:   /orders/:id/update
  param: { module: order, action: update }
  requirements: { id: \d+ }

order-print:
  url:   /orders/:id/print
  param: { module: order, action: print }
  requirements: { id: \d+ }

order-printaccount:
  url:   /orders/:id/print-account
  param: { module: order, action: printAccount }
  requirements: { id: \d+ }

order-printinvoice:
  url:   /orders/:id/print-invoice
  param: { module: order, action: printInvoice }
  requirements: { id: \d+ }

order-printwaybill:
  url:   /orders/:id/print-waybill
  param: { module: order, action: printWaybill }
  requirements: { id: \d+ }

comment:
  url:   /orders/:id/comment
  param: { module: order, action: comment }
  requirements: { id: \d+ }

comment-unread:
  url:   /orders/comment/unread
  param: { module: order, action: unread }

comment-delete:
  url:   /orders/:order/comment/:id/delete
  param: { module: order, action: deleteComment }
  requirements: { order: \d+, id: \d+ }

reports:
  url:   /reports
  param: { module: report, action: index }

report-costs:
  url:   /reports/costs
  param: { module: report, action: costs }

report-costs-active:
  url:   /reports/costs/active
  param: { module: report, action: costsActive }

report-managers:
  url:   /reports/managers
  param: { module: report, action: managers }

report-workers:
  url:   /reports/workers
  param: { module: report, action: workers }

report-clients:
  url:   /reports/clients
  param: { module: report, action: clients }

report-debt:
  url:   /reports/debt
  param: { module: report, action: debt }

users-show:
  url:   /users
  param: { module: users, action: index }

users-settings:
  url:   /users/settings
  param: { module: users, action: settings  }

users-create:
  url:   /users/create
  param: { module: users, action: create }

export:
  url:   /export
  param: { module: report, action: exportTo1C }

do-export:
  url:   /do-export
  param: { module: report, action: doExport }

users-edit:
  url:   /users/edit
  param: { module: users, action: edit }
  # generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
