<?php

/**
 * sfGuardPermissionTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardPermissionTable extends PluginsfGuardPermissionTable
{
    const CAN_VIEW_COSTS = 'can view costs';
    const CAN_EDIT_COSTS = 'can edit costs';

    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardPermission');
    }
}
