<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function getManagers()
    {
      return Doctrine_Core::getTable('sfGuardGroup')->createQuery('a, a.Users')
        ->where('a.name = ?', 'manager')
        ->orderBy('a.Users.last_name')
        ->execute()
          ->getFirst()
            ->getUsers()
      ;
    }
}