<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    xxi
 * @subpackage model
 * @author     Anatoly Pashin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function getOrdersTableSettings() {
    $settings = $this->_get('OrdersTableSettings');
    if ($settings->getId() === null) {
      $settings->save();
    }

    return $settings;
  }
}
