<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('order', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'client_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'due_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'approved_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'files' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'installation_cost' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'design_cost' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'contractors_cost' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'cost' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'started_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'finished_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'submited_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'state' => 
             array(
              'type' => 'enum',
              'notnull' => '1',
              'values' => 
              array(
              0 => 'calculating',
              1 => 'work',
              2 => 'working',
              3 => 'done',
              4 => 'submited',
              5 => 'archived',
              6 => 'debt',
              ),
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('order');
    }
}