<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'pay_method', 'enum', '', array(
             'values' => 
             array(
              0 => 'cash',
              1 => 'non-cash',
             ),
             ));
        $this->addColumn('order', 'recoil', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'pay_method');
        $this->removeColumn('order', 'recoil');
    }
}