<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('order_log', 'order_log_id_order_id', array(
             'name' => 'order_log_id_order_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'order',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('order_log', 'order_log_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('order_log', 'order_log_id_order_id');
        $this->removeIndex('order_log', 'order_log_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}