<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'payed', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'payed');
    }
}