<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('client', 'full_name', 'string', '255', array(
             ));
        $this->addColumn('client', 'ownership', 'enum', '', array(
             'values' => 
             array(
              0 => '',
              1 => 'ooo',
              2 => 'oao',
              3 => 'zao',
              4 => 'ip',
              5 => 'fiz',
             ),
             ));
        $this->addColumn('client', 'address_jure', 'string', '255', array(
             ));
        $this->addColumn('client', 'inn', 'string', '32', array(
             ));
        $this->addColumn('client', 'kpp', 'string', '32', array(
             ));
        $this->addColumn('client', 'rs', 'string', '32', array(
             ));
        $this->addColumn('client', 'bank', 'string', '255', array(
             ));
        $this->addColumn('client', 'bik', 'string', '32', array(
             ));
        $this->addColumn('client', 'ks', 'string', '32', array(
             ));
        $this->addColumn('client', 'ogrn', 'string', '32', array(
             ));
        $this->addColumn('client', 'okpo', 'string', '32', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('client', 'full_name');
        $this->removeColumn('client', 'ownership');
        $this->removeColumn('client', 'address_jure');
        $this->removeColumn('client', 'inn');
        $this->removeColumn('client', 'kpp');
        $this->removeColumn('client', 'rs');
        $this->removeColumn('client', 'bank');
        $this->removeColumn('client', 'bik');
        $this->removeColumn('client', 'ks');
        $this->removeColumn('client', 'ogrn');
        $this->removeColumn('client', 'okpo');
    }
}