<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'expected_at', 'timestamp', '25', array(
             ));
        $this->addColumn('order_auto_version', 'expected_at', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'expected_at');
        $this->removeColumn('order_auto_version', 'expected_at');
    }
}