<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comment_reads', 'comment_reads_user_id_sf_guard_user_id', array(
             'name' => 'comment_reads_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('comment_reads', 'comment_reads_comment_id_comment_id', array(
             'name' => 'comment_reads_comment_id_comment_id',
             'local' => 'comment_id',
             'foreign' => 'id',
             'foreignTable' => 'comment',
             ));
        $this->addIndex('comment_reads', 'comment_reads_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('comment_reads', 'comment_reads_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comment_reads', 'comment_reads_user_id_sf_guard_user_id');
        $this->dropForeignKey('comment_reads', 'comment_reads_comment_id_comment_id');
        $this->removeIndex('comment_reads', 'comment_reads_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('comment_reads', 'comment_reads_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
    }
}