<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('comment_reads', 'unique_for_inserts', array(
             'fields' => 
             array(
              0 => 'comment_id',
              1 => 'user_id',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('comment_reads', 'unique_for_inserts', array(
             'fields' => 
             array(
              0 => 'comment_id',
              1 => 'user_id',
             ),
             'type' => 'unique',
             ));
    }
}