<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('order', 'installation_cost', 'integer', '8', array(
             ));
        $this->changeColumn('order', 'design_cost', 'integer', '8', array(
             ));
        $this->changeColumn('order', 'contractors_cost', 'integer', '8', array(
             ));
        $this->changeColumn('order', 'delivery_cost', 'integer', '8', array(
             ));
        $this->changeColumn('order', 'cost', 'integer', '8', array(
             ));
        $this->changeColumn('order', 'recoil', 'integer', '8', array(
             ));
        $this->changeColumn('order', 'payed', 'integer', '8', array(
             ));
        $this->changeColumn('order_auto_version', 'installation_cost', 'integer', '8', array(
             ));
        $this->changeColumn('order_auto_version', 'design_cost', 'integer', '8', array(
             ));
        $this->changeColumn('order_auto_version', 'contractors_cost', 'integer', '8', array(
             ));
        $this->changeColumn('order_auto_version', 'delivery_cost', 'integer', '8', array(
             ));
        $this->changeColumn('order_auto_version', 'cost', 'integer', '8', array(
             ));
        $this->changeColumn('order_auto_version', 'recoil', 'integer', '8', array(
             ));
        $this->changeColumn('order_auto_version', 'payed', 'integer', '8', array(
             ));
    }

    public function down()
    {

    }
}