<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'additional', 'clob', '', array(
             ));
        $this->addColumn('order_auto_version', 'additional', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'additional');
        $this->removeColumn('order_auto_version', 'additional');
    }
}