<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'area', 'enum', '', array(
             'values' => 
             array(
              0 => 'pvc',
              1 => 'laser',
              2 => 'engraver',
              3 => 'mymaka',
              4 => 'outdoor',
              5 => 'lfp',
              6 => 'sublimation',
              7 => 'cutter',
              8 => 'serigraphy',
             ),
             ));
        $this->addColumn('order_auto_version', 'area', 'enum', '', array(
             'values' => 
             array(
              0 => 'pvc',
              1 => 'laser',
              2 => 'engraver',
              3 => 'mymaka',
              4 => 'outdoor',
              5 => 'lfp',
              6 => 'sublimation',
              7 => 'cutter',
              8 => 'serigraphy',
             ),
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'area');
        $this->removeColumn('order_auto_version', 'area');
    }
}