<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('client', 'discount', 'string', '4', array(
             ));
        $this->addColumn('client', 'buhgalter', 'string', '128', array(
             ));
        $this->addColumn('client', 'buhgalter_phone', 'string', '32', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('client', 'discount');
        $this->removeColumn('client', 'buhgalter');
        $this->removeColumn('client', 'buhgalter_phone');
    }
}