<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('client', 'deleted_at', array(
             'fields' => 
             array(
              0 => 'deleted_at',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('client', 'deleted_at', array(
             'fields' => 
             array(
              0 => 'deleted_at',
             ),
             ));
    }
}