<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('order', 'kasha_malasha', array(
             'fields' => 
             array(
              0 => 'submited_at',
              1 => 'finished_at',
              2 => 'payed_at',
              3 => 'started_at',
              4 => 'expected_at',
              5 => 'due_date',
              6 => 'created_at',
             ),
             ));
        $this->addIndex('order', 'bills', array(
             'fields' => 
             array(
              0 => 'bill_made',
              1 => 'bill_given',
             ),
             ));
        $this->addIndex('order', 'area', array(
             'fields' => 
             array(
              0 => 'area',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('order', 'kasha_malasha', array(
             'fields' => 
             array(
              0 => 'submited_at',
              1 => 'finished_at',
              2 => 'payed_at',
              3 => 'started_at',
              4 => 'expected_at',
              5 => 'due_date',
              6 => 'created_at',
             ),
             ));
        $this->removeIndex('order', 'bills', array(
             'fields' => 
             array(
              0 => 'bill_made',
              1 => 'bill_given',
             ),
             ));
        $this->removeIndex('order', 'area', array(
             'fields' => 
             array(
              0 => 'area',
             ),
             ));
    }
}