<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('order', 'state', array(
             'fields' => 
             array(
              0 => 'state',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('order', 'state', array(
             'fields' => 
             array(
              0 => 'state',
             ),
             ));
    }
}