<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('order', 'state', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'calculating',
              1 => 'work',
              2 => 'prepress',
              3 => 'working',
              4 => 'done',
              5 => 'submited',
              6 => 'archived',
              7 => 'debt',
             ),
             ));
        $this->changeColumn('order_auto_version', 'state', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'calculating',
              1 => 'work',
              2 => 'prepress',
              3 => 'working',
              4 => 'done',
              5 => 'submited',
              6 => 'archived',
              7 => 'debt',
             ),
             ));
    }

    public function down()
    {

    }
}