<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'execution_time', 'time', '25', array(
             ));
        $this->addColumn('order_auto_version', 'execution_time', 'time', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'execution_time');
        $this->removeColumn('order_auto_version', 'execution_time');
    }
}