<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version33 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('invoice', 'invoice_order_id_order_id_1', array(
             'name' => 'invoice_order_id_order_id_1',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'order',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('invoice', 'invoice_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('invoice', 'invoice_order_id_order_id_1');
        $this->removeIndex('invoice', 'invoice_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }
}