<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('invoice', 'number', 'float', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('invoice', 'price', 'float', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('invoice', 'sum', 'float', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}