<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('compamy_settings');
        $this->addColumn('order', 'waybill_number', 'integer', '8', array(
             ));
        $this->addColumn('order_auto_version', 'waybill_number', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->createTable('compamy_settings', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'full_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'phone' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'address_jure' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'inn' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'kpp' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'rs' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'bank' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'bik' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'ks' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'ogrn' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'okpo' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'buhgalter' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'director' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'created_by' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->removeColumn('order', 'waybill_number');
        $this->removeColumn('order_auto_version', 'waybill_number');
    }
}