<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('utilization', 'utilization_order_id_order_id', array(
             'name' => 'utilization_order_id_order_id',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'order',
             ));
        $this->createForeignKey('utilization', 'utilization_material_id_material_id', array(
             'name' => 'utilization_material_id_material_id',
             'local' => 'material_id',
             'foreign' => 'id',
             'foreignTable' => 'material',
             ));
        $this->addIndex('utilization', 'utilization_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
        $this->addIndex('utilization', 'utilization_material_id', array(
             'fields' => 
             array(
              0 => 'material_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('utilization', 'utilization_order_id_order_id');
        $this->dropForeignKey('utilization', 'utilization_material_id_material_id');
        $this->removeIndex('utilization', 'utilization_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
        $this->removeIndex('utilization', 'utilization_material_id', array(
             'fields' => 
             array(
              0 => 'material_id',
             ),
             ));
    }
}