<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('material', 'material_dimension_id_dimension_id', array(
             'name' => 'material_dimension_id_dimension_id',
             'local' => 'dimension_id',
             'foreign' => 'id',
             'foreignTable' => 'dimension',
             ));
        $this->createForeignKey('ref_supplier_material', 'ref_supplier_material_supplier_id_supplier_id', array(
             'name' => 'ref_supplier_material_supplier_id_supplier_id',
             'local' => 'supplier_id',
             'foreign' => 'id',
             'foreignTable' => 'supplier',
             ));
        $this->createForeignKey('ref_supplier_material', 'ref_supplier_material_material_id_material_id', array(
             'name' => 'ref_supplier_material_material_id_material_id',
             'local' => 'material_id',
             'foreign' => 'id',
             'foreignTable' => 'material',
             ));
        $this->addIndex('material', 'material_dimension_id', array(
             'fields' => 
             array(
              0 => 'dimension_id',
             ),
             ));
        $this->addIndex('ref_supplier_material', 'ref_supplier_material_supplier_id', array(
             'fields' => 
             array(
              0 => 'supplier_id',
             ),
             ));
        $this->addIndex('ref_supplier_material', 'ref_supplier_material_material_id', array(
             'fields' => 
             array(
              0 => 'material_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('material', 'material_dimension_id_dimension_id');
        $this->dropForeignKey('ref_supplier_material', 'ref_supplier_material_supplier_id_supplier_id');
        $this->dropForeignKey('ref_supplier_material', 'ref_supplier_material_material_id_material_id');
        $this->removeIndex('material', 'material_dimension_id', array(
             'fields' => 
             array(
              0 => 'dimension_id',
             ),
             ));
        $this->removeIndex('ref_supplier_material', 'ref_supplier_material_supplier_id', array(
             'fields' => 
             array(
              0 => 'supplier_id',
             ),
             ));
        $this->removeIndex('ref_supplier_material', 'ref_supplier_material_material_id', array(
             'fields' => 
             array(
              0 => 'material_id',
             ),
             ));
    }
}