<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('utilization', 'amount', 'decimal', '18', array(
             'notnull' => '1',
             'scale' => '4',
             'default' => '0.0000',
             ));
    }

    public function down()
    {

    }
}