<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('utilization', 'created_by', 'integer', '8', array(
             ));
        $this->addColumn('utilization', 'updated_by', 'integer', '8', array(
             ));
        $this->addColumn('utilization', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('utilization', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('utilization', 'created_by');
        $this->removeColumn('utilization', 'updated_by');
        $this->removeColumn('utilization', 'created_at');
        $this->removeColumn('utilization', 'updated_at');
    }
}