<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version49 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('material', 'price', 'decimal', '18', array(
             'notnull' => '1',
             'scale' => '2',
             ));
    }

    public function down()
    {
        $this->removeColumn('material', 'price');
    }
}