<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('ref_supplier_material');
        $this->createTable('arrival', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'material_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'supplier_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'count' => 
             array(
              'type' => 'decimal',
              'notnull' => '1',
              'scale' => '4',
              'length' => '18',
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'notnull' => '1',
              'scale' => '2',
              'length' => '18',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeColumn('material', 'price');
    }

    public function down()
    {
        $this->createTable('ref_supplier_material', array(
             'supplier_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'material_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'supplier_id',
              1 => 'material_id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->dropTable('arrival');
        $this->addColumn('material', 'price', 'decimal', '18', array(
             'notnull' => '1',
             'scale' => '2',
             ));
    }
}