<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version51 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('arrival', 'arrival_material_id_material_id', array(
             'name' => 'arrival_material_id_material_id',
             'local' => 'material_id',
             'foreign' => 'id',
             'foreignTable' => 'material',
             ));
        $this->createForeignKey('arrival', 'arrival_supplier_id_supplier_id', array(
             'name' => 'arrival_supplier_id_supplier_id',
             'local' => 'supplier_id',
             'foreign' => 'id',
             'foreignTable' => 'supplier',
             ));
        $this->createForeignKey('arrival', 'arrival_created_by_sf_guard_user_id', array(
             'name' => 'arrival_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('arrival', 'arrival_updated_by_sf_guard_user_id', array(
             'name' => 'arrival_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('arrival', 'arrival_material_id', array(
             'fields' => 
             array(
              0 => 'material_id',
             ),
             ));
        $this->addIndex('arrival', 'arrival_supplier_id', array(
             'fields' => 
             array(
              0 => 'supplier_id',
             ),
             ));
        $this->addIndex('arrival', 'arrival_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('arrival', 'arrival_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('arrival', 'arrival_material_id_material_id');
        $this->dropForeignKey('arrival', 'arrival_supplier_id_supplier_id');
        $this->dropForeignKey('arrival', 'arrival_created_by_sf_guard_user_id');
        $this->dropForeignKey('arrival', 'arrival_updated_by_sf_guard_user_id');
        $this->removeIndex('arrival', 'arrival_material_id', array(
             'fields' => 
             array(
              0 => 'material_id',
             ),
             ));
        $this->removeIndex('arrival', 'arrival_supplier_id', array(
             'fields' => 
             array(
              0 => 'supplier_id',
             ),
             ));
        $this->removeIndex('arrival', 'arrival_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('arrival', 'arrival_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
    }
}