<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version56 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ref_utilization_arrival', 'ref_utilization_arrival_utilization_id_utilization_id', array(
             'name' => 'ref_utilization_arrival_utilization_id_utilization_id',
             'local' => 'utilization_id',
             'foreign' => 'id',
             'foreignTable' => 'utilization',
             ));
        $this->createForeignKey('ref_utilization_arrival', 'ref_utilization_arrival_arrival_id_arrival_id', array(
             'name' => 'ref_utilization_arrival_arrival_id_arrival_id',
             'local' => 'arrival_id',
             'foreign' => 'id',
             'foreignTable' => 'arrival',
             ));
        $this->addIndex('ref_utilization_arrival', 'ref_utilization_arrival_utilization_id', array(
             'fields' => 
             array(
              0 => 'utilization_id',
             ),
             ));
        $this->addIndex('ref_utilization_arrival', 'ref_utilization_arrival_arrival_id', array(
             'fields' => 
             array(
              0 => 'arrival_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ref_utilization_arrival', 'ref_utilization_arrival_utilization_id_utilization_id');
        $this->dropForeignKey('ref_utilization_arrival', 'ref_utilization_arrival_arrival_id_arrival_id');
        $this->removeIndex('ref_utilization_arrival', 'ref_utilization_arrival_utilization_id', array(
             'fields' => 
             array(
              0 => 'utilization_id',
             ),
             ));
        $this->removeIndex('ref_utilization_arrival', 'ref_utilization_arrival_arrival_id', array(
             'fields' => 
             array(
              0 => 'arrival_id',
             ),
             ));
    }
}