<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version54 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('arrival', 'spent', 'decimal', '18', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '4',
             ));
    }

    public function down()
    {
        $this->removeColumn('arrival', 'spent');
    }
}