<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version53 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('arrival', 'count');
        $this->addColumn('arrival', 'amount', 'decimal', '18', array(
             'notnull' => '1',
             'scale' => '4',
             ));
    }

    public function down()
    {
        $this->addColumn('arrival', 'count', 'decimal', '18', array(
             'notnull' => '1',
             'scale' => '4',
             ));
        $this->removeColumn('arrival', 'amount');
    }
}