<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version55 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ref_utilization_arrival', array(
             'utilization_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'arrival_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'amount' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'utilization_id',
              1 => 'arrival_id',
             ),
             ));
        $this->removeColumn('arrival', 'spent');
    }

    public function down()
    {
        $this->dropTable('ref_utilization_arrival');
        $this->addColumn('arrival', 'spent', 'decimal', '18', array(
             'default' => '0',
             'notnull' => '1',
             'scale' => '4',
             ));
    }
}