<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version58 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('pay', 'pay_order_id_order_id', array(
             'name' => 'pay_order_id_order_id',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'order',
             ));
        $this->createForeignKey('pay', 'pay_created_by_sf_guard_user_id', array(
             'name' => 'pay_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('pay', 'pay_updated_by_sf_guard_user_id', array(
             'name' => 'pay_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('pay', 'pay_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
        $this->addIndex('pay', 'pay_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('pay', 'pay_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('pay', 'pay_order_id_order_id');
        $this->dropForeignKey('pay', 'pay_created_by_sf_guard_user_id');
        $this->dropForeignKey('pay', 'pay_updated_by_sf_guard_user_id');
        $this->removeIndex('pay', 'pay_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
        $this->removeIndex('pay', 'pay_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('pay', 'pay_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
    }
}