<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version52 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('arrival', 'arrived_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('arrival', 'bill', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('arrival', 'arrived_at');
        $this->removeColumn('arrival', 'bill');
    }
}