<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('contractor', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'full_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'contact' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'phone' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'address_jure' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'inn' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'kpp' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'rs' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'bank' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'bik' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'ks' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'ogrn' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'okpo' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'discount' => 
             array(
              'type' => 'string',
              'length' => '4',
             ),
             'buhgalter' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'buhgalter_phone' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('contractor');
    }
}