<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version63 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('area', 'area_created_by_sf_guard_user_id', array(
             'name' => 'area_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('area', 'area_updated_by_sf_guard_user_id', array(
             'name' => 'area_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('work', 'work_area_id_area_id', array(
             'name' => 'work_area_id_area_id',
             'local' => 'area_id',
             'foreign' => 'id',
             'foreignTable' => 'area',
             ));
        $this->createForeignKey('work', 'work_created_by_sf_guard_user_id', array(
             'name' => 'work_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('work', 'work_updated_by_sf_guard_user_id', array(
             'name' => 'work_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('area', 'area_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('area', 'area_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
        $this->addIndex('work', 'work_area_id', array(
             'fields' => 
             array(
              0 => 'area_id',
             ),
             ));
        $this->addIndex('work', 'work_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('work', 'work_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('area', 'area_created_by_sf_guard_user_id');
        $this->dropForeignKey('area', 'area_updated_by_sf_guard_user_id');
        $this->dropForeignKey('work', 'work_area_id_area_id');
        $this->dropForeignKey('work', 'work_created_by_sf_guard_user_id');
        $this->dropForeignKey('work', 'work_updated_by_sf_guard_user_id');
        $this->removeIndex('area', 'area_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('area', 'area_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
        $this->removeIndex('work', 'work_area_id', array(
             'fields' => 
             array(
              0 => 'area_id',
             ),
             ));
        $this->removeIndex('work', 'work_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('work', 'work_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
    }
}