<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version71 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ref_order_work', 'area_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('ref_order_work', 'master_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('ref_order_work', 'area_id');
        $this->removeColumn('ref_order_work', 'master_id');
    }
}