<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version73 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ref_order_work', 'finished_at', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('ref_order_work', 'finished_at');
    }
}