<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version70 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('area', 'style', 'clob', '', array(
             ));

        /* new permission for styling areas */
        $permission = new sfGuardPermission();
        $permission->setName('can_edit_styles_of_areas')->save();
    }

    public function down()
    {
        $this->removeColumn('area', 'style');
    }
}