<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version65 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ref_order_work', 'ref_order_work_created_by_sf_guard_user_id', array(
             'name' => 'ref_order_work_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('ref_order_work', 'ref_order_work_updated_by_sf_guard_user_id', array(
             'name' => 'ref_order_work_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('ref_order_work', 'ref_order_work_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('ref_order_work', 'ref_order_work_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));

        /* new permission for worker */
        $permission = new sfGuardPermission();
        $permission->setName('can_set_order_works')->save();

        $worker = Doctrine_Core::getTable('sfGuardGroup')->findOneByName('worker');
        $worker->link('Permissions', [$permission->getId()]);
        $worker->save();
    }

    public function down()
    {
        $this->dropForeignKey('ref_order_work', 'ref_order_work_created_by_sf_guard_user_id');
        $this->dropForeignKey('ref_order_work', 'ref_order_work_updated_by_sf_guard_user_id');
        $this->removeIndex('ref_order_work', 'ref_order_work_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('ref_order_work', 'ref_order_work_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
    }
}