<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version67 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('area', 'slug', 'string', '255', array(
             'default' => '',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('area', 'slug');
    }
}