<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version75 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('utilization', 'utilization_work_id_ref_order_work_id', array(
             'name' => 'utilization_work_id_ref_order_work_id',
             'local' => 'work_id',
             'foreign' => 'id',
             'foreignTable' => 'ref_order_work',
             ));
        $this->addIndex('utilization', 'utilization_work_id', array(
             'fields' => 
             array(
              0 => 'work_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('utilization', 'utilization_work_id_ref_order_work_id');
        $this->removeIndex('utilization', 'utilization_work_id', array(
             'fields' => 
             array(
              0 => 'work_id',
             ),
             ));
    }
}