<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version76 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('order', 'state', 'enum', '', array(
             'notnull' => '1',
             'values' =>
             array(
              0 => 'calculating',
              1 => 'work',
              2 => 'working',
              3 => 'done',
              4 => 'submited',
              5 => 'archived',
              6 => 'debt',
              7 => 'prepress',
              8 => 'deleted',
             ),
             ));
        $this->changeColumn('order_auto_version', 'state', 'enum', '', array(
             'notnull' => '1',
             'values' =>
             array(
              0 => 'calculating',
              1 => 'work',
              2 => 'working',
              3 => 'done',
              4 => 'submited',
              5 => 'archived',
              6 => 'debt',
              7 => 'prepress',
              8 => 'deleted',
             ),
             ));

        /* new permission for deleting and undeleting orders */
        $permission = new sfGuardPermission();
        $permission->setName('can-delete-orders')->save();
    }

    public function down()
    {

    }
}