<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version78 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ref_area_worker', 'ref_area_worker_area_id_area_id', array(
             'name' => 'ref_area_worker_area_id_area_id',
             'local' => 'area_id',
             'foreign' => 'id',
             'foreignTable' => 'area',
             ));
        $this->createForeignKey('ref_area_worker', 'ref_area_worker_user_id_sf_guard_user_id', array(
             'name' => 'ref_area_worker_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('ref_area_worker', 'ref_area_worker_area_id', array(
             'fields' => 
             array(
              0 => 'area_id',
             ),
             ));
        $this->addIndex('ref_area_worker', 'ref_area_worker_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ref_area_worker', 'ref_area_worker_area_id_area_id');
        $this->dropForeignKey('ref_area_worker', 'ref_area_worker_user_id_sf_guard_user_id');
        $this->removeIndex('ref_area_worker', 'ref_area_worker_area_id', array(
             'fields' => 
             array(
              0 => 'area_id',
             ),
             ));
        $this->removeIndex('ref_area_worker', 'ref_area_worker_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}