<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version79 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('order', 'state', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'calculating',
              1 => 'prepress',
              2 => 'prepress-working',
              3 => 'prepress-done',
              4 => 'work',
              5 => 'working',
              6 => 'done',
              7 => 'submited',
              8 => 'archived',
              9 => 'debt',
              10 => 'deleted',
             ),
             ));
        $this->changeColumn('order_auto_version', 'state', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'calculating',
              1 => 'prepress',
              2 => 'prepress-working',
              3 => 'prepress-done',
              4 => 'work',
              5 => 'working',
              6 => 'done',
              7 => 'submited',
              8 => 'archived',
              9 => 'debt',
              10 => 'deleted',
             ),
             ));
    }

    public function down()
    {

    }
}