<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version77 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ref_area_worker', array(
             'area_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'area_id',
              1 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ref_area_worker');
    }
}