<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version80 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('area', 'rate', 'decimal', '18', array(
             'scale' => '2',
             ));
    }

    public function down()
    {
        $this->removeColumn('area', 'rate');
    }
}