<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version83 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('material_movement', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'type' =>
             array(
              'type' => 'enum',
              'values' =>
              array(
              0 => 'arrival',
              1 => 'transfer',
              2 => 'utilization',
              3 => 'writeoff',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'from_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'to_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'arrival_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'transfer_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'utilization_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'writeoff_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'deleted_at' =>
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('material_movement_materials', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'movement_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'material_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'amount' =>
             array(
              'type' => 'decimal',
              'scale' => '4',
              'notnull' => '1',
              'length' => '18',
             ),
             'price' =>
             array(
              'type' => 'decimal',
              'scale' => '2',
              'notnull' => '1',
              'length' => '18',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'deleted_at' =>
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('material_movement');
        $this->dropTable('material_movement_materials');
    }
}
