<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version92 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('material_movement', 'material_movement_arrival_id_material_movement_arrival_id', array(
             'name' => 'material_movement_arrival_id_material_movement_arrival_id',
             'local' => 'arrival_id',
             'foreign' => 'id',
             'foreignTable' => 'material_movement_arrival',
             ));
        $this->createForeignKey('material_movement_arrival', 'material_movement_arrival_supplier_id_supplier_id', array(
             'name' => 'material_movement_arrival_supplier_id_supplier_id',
             'local' => 'supplier_id',
             'foreign' => 'id',
             'foreignTable' => 'supplier',
             ));
        $this->createForeignKey('material_movement_arrival', 'material_movement_arrival_created_by_sf_guard_user_id', array(
             'name' => 'material_movement_arrival_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('material_movement_arrival', 'material_movement_arrival_updated_by_sf_guard_user_id', array(
             'name' => 'material_movement_arrival_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('material_movement', 'material_movement_arrival_id', array(
             'fields' =>
             array(
              0 => 'arrival_id',
             ),
             ));
        $this->addIndex('material_movement_arrival', 'material_movement_arrival_supplier_id', array(
             'fields' =>
             array(
              0 => 'supplier_id',
             ),
             ));
        $this->addIndex('material_movement_arrival', 'material_movement_arrival_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('material_movement_arrival', 'material_movement_arrival_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('material_movement', 'material_movement_arrival_id_material_movement_arrival_id');
        $this->dropForeignKey('material_movement_arrival', 'material_movement_arrival_supplier_id_supplier_id');
        $this->dropForeignKey('material_movement_arrival', 'material_movement_arrival_created_by_sf_guard_user_id');
        $this->dropForeignKey('material_movement_arrival', 'material_movement_arrival_updated_by_sf_guard_user_id');
        $this->removeIndex('material_movement', 'material_movement_arrival_id', array(
             'fields' =>
             array(
              0 => 'arrival_id',
             ),
             ));
        $this->removeIndex('material_movement_arrival', 'material_movement_arrival_supplier_id', array(
             'fields' =>
             array(
              0 => 'supplier_id',
             ),
             ));
        $this->removeIndex('material_movement_arrival', 'material_movement_arrival_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('material_movement_arrival', 'material_movement_arrival_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
    }
}
