<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version84 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('material_movement', 'material_movement_to_id_warehouse_id', array(
             'name' => 'material_movement_to_id_warehouse_id',
             'local' => 'to_id',
             'foreign' => 'id',
             'foreignTable' => 'warehouse',
             ));
        $this->createForeignKey('material_movement', 'material_movement_from_id_warehouse_id', array(
             'name' => 'material_movement_from_id_warehouse_id',
             'local' => 'from_id',
             'foreign' => 'id',
             'foreignTable' => 'warehouse',
             ));
        $this->createForeignKey('material_movement', 'material_movement_created_by_sf_guard_user_id', array(
             'name' => 'material_movement_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('material_movement', 'material_movement_updated_by_sf_guard_user_id', array(
             'name' => 'material_movement_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('material_movement_materials', 'material_movement_materials_material_id_material_id', array(
             'name' => 'material_movement_materials_material_id_material_id',
             'local' => 'material_id',
             'foreign' => 'id',
             'foreignTable' => 'material',
             ));
        $this->createForeignKey('material_movement_materials', 'material_movement_materials_movement_id_material_movement_id', array(
             'name' => 'material_movement_materials_movement_id_material_movement_id',
             'local' => 'movement_id',
             'foreign' => 'id',
             'foreignTable' => 'material_movement',
             ));
        $this->createForeignKey('material_movement_materials', 'material_movement_materials_created_by_sf_guard_user_id', array(
             'name' => 'material_movement_materials_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('material_movement_materials', 'material_movement_materials_updated_by_sf_guard_user_id', array(
             'name' => 'material_movement_materials_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('material_movement', 'material_movement_to_id', array(
             'fields' =>
             array(
              0 => 'to_id',
             ),
             ));
        $this->addIndex('material_movement', 'material_movement_from_id', array(
             'fields' =>
             array(
              0 => 'from_id',
             ),
             ));
        $this->addIndex('material_movement', 'material_movement_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('material_movement', 'material_movement_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
        $this->addIndex('material_movement_materials', 'material_movement_materials_material_id', array(
             'fields' =>
             array(
              0 => 'material_id',
             ),
             ));
        $this->addIndex('material_movement_materials', 'material_movement_materials_movement_id', array(
             'fields' =>
             array(
              0 => 'movement_id',
             ),
             ));
        $this->addIndex('material_movement_materials', 'material_movement_materials_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('material_movement_materials', 'material_movement_materials_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('material_movement', 'material_movement_to_id_warehouse_id');
        $this->dropForeignKey('material_movement', 'material_movement_from_id_warehouse_id');
        $this->dropForeignKey('material_movement', 'material_movement_created_by_sf_guard_user_id');
        $this->dropForeignKey('material_movement', 'material_movement_updated_by_sf_guard_user_id');
        $this->dropForeignKey('material_movement_materials', 'material_movement_materials_material_id_material_id');
        $this->dropForeignKey('material_movement_materials', 'material_movement_materials_movement_id_material_movement_id');
        $this->dropForeignKey('material_movement_materials', 'material_movement_materials_created_by_sf_guard_user_id');
        $this->dropForeignKey('material_movement_materials', 'material_movement_materials_updated_by_sf_guard_user_id');
        $this->removeIndex('material_movement', 'material_movement_to_id', array(
             'fields' =>
             array(
              0 => 'to_id',
             ),
             ));
        $this->removeIndex('material_movement', 'material_movement_from_id', array(
             'fields' =>
             array(
              0 => 'from_id',
             ),
             ));
        $this->removeIndex('material_movement', 'material_movement_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('material_movement', 'material_movement_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
        $this->removeIndex('material_movement_materials', 'material_movement_materials_material_id', array(
             'fields' =>
             array(
              0 => 'material_id',
             ),
             ));
        $this->removeIndex('material_movement_materials', 'material_movement_materials_movement_id', array(
             'fields' =>
             array(
              0 => 'movement_id',
             ),
             ));
        $this->removeIndex('material_movement_materials', 'material_movement_materials_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('material_movement_materials', 'material_movement_materials_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
    }
}
