<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version93 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('material_movement_utilization', 'material_movement_utilization_work_id_work_id');
        $this->createForeignKey('material_movement_utilization', 'material_movement_utilization_work_id_ref_order_work_id', array(
             'name' => 'material_movement_utilization_work_id_ref_order_work_id',
             'local' => 'work_id',
             'foreign' => 'id',
             'foreignTable' => 'ref_order_work',
             ));
    }

    public function down()
    {
        $this->createForeignKey('material_movement_utilization', 'material_movement_utilization_work_id_work_id', array(
             'name' => 'material_movement_utilization_work_id_work_id',
             'local' => 'work_id',
             'foreign' => 'id',
             'foreignTable' => 'work',
             ));
        $this->dropForeignKey('material_movement_utilization', 'material_movement_utilization_work_id_ref_order_work_id');
    }
}
