<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version96 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('client', 'discount', 'integer', '2', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}
