<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version97 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('utilization_plan', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'order_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'material_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'amount' =>
             array(
              'type' => 'decimal',
              'scale' => '4',
              'notnull' => '1',
              'length' => '18',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'deleted_at' =>
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('utilization_plan');
    }
}
