<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version99 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('utilization_plan', 'utilization_plan_material_id_material_id', array(
             'name' => 'utilization_plan_material_id_material_id',
             'local' => 'material_id',
             'foreign' => 'id',
             'foreignTable' => 'material',
             ));
        $this->addIndex('utilization_plan', 'utilization_plan_material_id', array(
             'fields' =>
             array(
              0 => 'material_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('utilization_plan', 'utilization_plan_material_id_material_id');
        $this->removeIndex('utilization_plan', 'utilization_plan_material_id', array(
             'fields' =>
             array(
              0 => 'material_id',
             ),
             ));
    }
}
