<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version100 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('material_movement_materials', 'description', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('material_movement_materials', 'description');
    }
}
