<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version104 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('client', 'discount', 'integer', '2', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->changeColumn('invoice', 'number', 'decimal', '18', array(
             'notnull' => '1',
             'default' => '0',
             'scale' => '2',
             ));
        $this->changeColumn('invoice', 'price', 'decimal', '18', array(
             'notnull' => '1',
             'default' => '0',
             'scale' => '2',
             ));
        $this->changeColumn('invoice', 'sum', 'decimal', '18', array(
             'notnull' => '1',
             'default' => '0',
             'scale' => '2',
             ));
        $this->changeColumn('pay', 'amount', 'decimal', '18', array(
             'notnull' => '1',
             'default' => '0',
             'scale' => '2',
             ));
    }

    public function down()
    {

    }
}
