<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version108 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('orders_table_settings', 'orders_table_settings_user_id_sf_guard_user_id', array(
             'name' => 'orders_table_settings_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('orders_table_settings', 'orders_table_settings_user_id', array(
             'fields' =>
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('orders_table_settings', 'orders_table_settings_user_id_sf_guard_user_id');
        $this->removeIndex('orders_table_settings', 'orders_table_settings_user_id', array(
             'fields' =>
             array(
              0 => 'user_id',
             ),
             ));
    }
}
