<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version109 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('orders_table_filter', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'is_default' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'fitler' =>
             array(
              'type' => 'array',
              'notnull' => '1',
              'length' => '',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('orders_table_filter');
    }
}
