<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version106 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('orders_table_settings', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'id_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'client_id_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'approved_at_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'due_date_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'submited_at_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'state_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'cost_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'payed_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'pay_method_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'payed_at_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'manager_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'bill_made_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'bill_given_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'docs_given_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             'comments_enabled' =>
             array(
              'type' => 'boolean',
              'default' => '1',
              'notnull' => '1',
              'length' => '25',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('orders_table_settings');
    }
}
