<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version112 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('orders_table_filter', 'fitler');
        $this->addColumn('orders_table_filter', 'filter', 'array', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('orders_table_filter', 'fitler', 'array', '', array(
             'notnull' => '1',
             ));
        $this->removeColumn('orders_table_filter', 'filter');
    }
}
