<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version107 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orders_table_settings', 'user_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('orders_table_settings', 'user_id');
    }
}
