all:
  credentials: [[manager, director, buhgalter]]

edit:
  credentials: [[manager, director]]

update:
  credentials: [[manager, director]]

new:
  credentials: [[manager, director]]

create:
  credentials: [[manager, director]]
