# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/06-Admin-Generator

generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 default
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          ~
    with_doctrine_route:   false
    actions_base_class:    sfActions
