Dimension:
  actAs:
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
  relations:
    Materials:
      class: Material
      type: many
      local: id
      foreign: dimension_id

Material:
  actAs:
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    dimension_id:
      type: integer
      notnull: true

Supplier:
  actAs:
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    full_name:
      type: string(255)
    contact:
      type: string(255)
      notnull: true
    phone:
      type: string(128)
      notnull: true
    email:
      type: string(64)
    address_jure:
      type: string(255)
    inn:
      type: string(32)
    kpp:
      type: string(32)
    rs:
      type: string(32)
    bank:
      type: string(255)
    bik:
      type: string(32)
    ks:
      type: string(32)
    ogrn:
      type: string(32)
    okpo:
      type: string(32)
    discount:
      type: string(4)
    buhgalter:
      type: string(128)
    buhgalter_phone:
      type: string(32)
  relations:
    Materials:
      class: Material
      refClass: RefSupplierMaterial
      local: supplier_id
      foreign: material_id
      foreignAlias: Suppliers

RefSupplierMaterial:
  columns:
    supplier_id:
      type: integer
      primary: true
    material_id:
      type: integer
      primary: true
  relations:
    Supplier:
      local: supplier_id
    Material:
      local: material_id

Utilization:
  columns:
    order_id:
      type: integer
      notnull: true
    material_id:
      type: integer
      notnull: true
    amount:
      type: decimal
      notnull: true
      scale: 4
  relations:
    Order:
      local: order_id
      foreign: id
      foreignAlias: Utilizations
    Material:
      local: material_id
      foreign: id
      foreignAlias: Utilizations
