# Приход материала
Arrival:
  actAs:
    SoftDelete: ~
    Timestampable: ~
    Signable: ~
  columns:
    arrived_at: # дата накладной
      type: timestamp
      notnull: true
    bill: # накладная
      type: string(255)
      notnull: true
    supplier_id:
      type: integer
      notnull: true
    material_id:
      type: integer
      notnull: true
    amount: # сколько пришло
      type: decimal
      notnull: true
      scale: 4
    price: # цена за 1
      type: decimal
      notnull: true
      scale: 2
  relations:
    Material:
      local: material_id
      foreign: id
      foreignAlias: Arrivals
    Supplier:
      local: supplier_id
      foreign: id
      foreignAlias: Arrivals

 # Размерность материала
Dimension:
  actAs:
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true

Material:
  actAs:
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    dimension_id:
      type: integer
      notnull: true
  relations:
    Dimension:
      local: dimension_id
      foreign: id
      foreignAlias: Materials

# Расход материала
Utilization:
  actAs:
    Signable: ~
    Timestampable: ~
  columns:
    order_id:
      type: integer
      notnull: true
    work_id:
      type: integer
      notnull: true
    material_id:
      type: integer
      notnull: true
    amount: # сколько затратили
      type: decimal
      notnull: true
      scale: 4
  relations:
    Order:
      local: order_id
      foreign: id
      foreignAlias: Utilizations
    Work:
      class: RefOrderWork
      local: work_id
      foreign: id
      foreignAlias: Utilizations
    Material:
      local: material_id
      foreign: id
      foreignAlias: Utilizations

# Из какого прихода сколько потратили материала
RefUtilizationArrival:
  columns:
    utilization_id:
      type: integer
      primary: true
    arrival_id:
      type: integer
      primary: true
    amount:
      type: integer
      notnull: true
  relations:
    Utilization:
      local: utilization_id
      foreign: id
    Arrival:
      local: arrival_id
      foreign: id
