Client:
  actAs: [Signable, SoftDelete]
  columns:
    name:
      type: string(255)
      notnull: true
    contact:
      type: string(255)
      notnull: true
    phone:
      type: string(128)
      notnull: true
    email:
      type: string(64)
  relations:
    Orders:
      class: Order
      type: many
      local: id
      foreign: client_id

Order:
  actAs:
    Timestampable:
      ~
    Signable:
      ~
    SoftDelete:
      ~
    Versionable:
      className: '%CLASS%Versionable'
      tableName: '%TABLE%_log'
      deleteVersions: false
      auditLog: true
      generateFiles: true
      generatePath: '<?php echo sfConfig::get("sf_lib_dir"); ?>/model/doctrine'

      builderOptions: <?php echo sfYamlInline::dump(ProjectConfiguration::getActive()->getPluginConfiguration('sfDoctrinePlugin')->getModelBuilderOptions()); ?>

  columns:
    client_id:
      type: integer
      notnull: true
    description:
      type: clob
      notnull: true
    due_date: timestamp
    approved_at: timestamp
    files: clob
    installation_cost: string(255)
    design_cost: string(255)
    contractors_cost: string(255)
    cost: string(255)
    pay_method:
      type: enum
      values:
        - ""
        - cash
        - non-cash
    recoil: string(255)
    payed: string(255)
    started_at: timestamp
    finished_at: timestamp
    submited_at: timestamp
    state:
      type: enum
      notnull: true
      values:
        - calculating
        - work
        - working
        - done
        - submited
        - archived
        - debt
  relations:
    Comments:
      class: Comment
      type: many
      local: id
      foreign: order_id

OrderVersionable:
  tableName: order_log
  columns:
    id:
      type: integer
      notnull: true
    client_id:
      type: integer
      notnull: true
    description:
      type: clob
      notnull: true
    due_date: timestamp
    approved_at: timestamp
    files: clob
    installation_cost: string(255)
    design_cost: string(255)
    contractors_cost: string(255)
    cost: string(255)
    pay_method:
      type: enum
      values:
        - ""
        - cash
        - non-cash
    recoil: string(255)
    payed: string(255)
    started_at: timestamp
    finished_at: timestamp
    submited_at: timestamp
    state:
      type: enum
      notnull: true
      values:
        - calculating
        - work
        - working
        - done
        - submited
        - archived
        - debt
    version: integer

Comment:
  actAs: [Timestampable, Signable]
  columns:
    order_id:
      type: integer
      notnull: true
    text:
      type: clob
      notnull: true
