Client:
  actAs: [Signable, SoftDelete]
  columns:
    name:
      type: string(255)
      notnull: true
    full_name:
      type: string(255)
    ownership:
      type: enum
      values:
        - ""
        - ooo
        - oao
        - zao
        - ip
        - fiz
    contact:
      type: string(255)
      notnull: true
    phone:
      type: string(128)
      notnull: true
    email:
      type: string(64)
    address_jure:
      type: string(255)
    inn:
      type: string(32)
    kpp:
      type: string(32)
    rs:
      type: string(32)
    bank:
      type: string(255)
    bik:
      type: string(32)
    ks:
      type: string(32)
    ogrn:
      type: string(32)
    okpo:
      type: string(32)
    discount:
      type: string(4)
    buhgalter:
      type: string(128)
    buhgalter_phone:
      type: string(32)
  relations:
    Orders:
      class: Order
      type: many
      local: id
      foreign: client_id
  indexes:
    deleted_at:
      fields: [deleted_at]

Order:
  actAs:
    Timestampable:
      ~
    Signable:
      ~
    SoftDelete:
      ~
    Versionable:
      className: '%CLASS%AutoVersion'
      deleteVersions: false
      auditLog: true

  columns:
    client_id:
      type: integer
      notnull: true
    description:
      type: clob
      notnull: true
    additional: clob
    due_date: timestamp
    approved_at: timestamp
    files: clob
    installation_cost: integer
    design_cost: integer
    contractors_cost: integer
    delivery_cost: integer
    cost: integer
    pay_method:
      type: enum
      values:
        - ""
        - cash
        - non-cash
        - barter
        - settlement
    recoil: integer
    payed: integer
    payed_at: timestamp
    expected_at: timestamp
    started_at: timestamp
    finished_at: timestamp
    submited_at: timestamp
    execution_time: time
    state:
      type: enum
      notnull: true
      values:
        - calculating
        - work
        - working
        - done
        - submited
        - archived
        - debt
        - prepress
    area:
      type: enum
      values:
        - pvc
        - laser
        - engraver
        - mymaka
        - outdoor
        - lfp
        - sublimation
        - cutter
        - serigraphy
    bill_made:
      type: boolean
      notnull: true
      default: false
    bill_given:
      type: boolean
      notnull: true
      default: false
    docs_given:
      type: boolean
      notnull: true
      default: false
  relations:
    Comments:
      class: Comment
      type: many
      local: id
      foreign: order_id
# Invoices:
# class: Invoice
# local: id
# foreign: order_id
# foreignAlias: Invoices
# foreignType: many
  indexes:
    state:
      fields: [state]
    deleted_at:
      fields: [deleted_at]
    kasha_malasha:
      fields: [submited_at, finished_at, payed_at, started_at, expected_at, due_date, created_at]
    bills:
      fields: [bill_made, bill_given]
    area:
      fields: [area]

Comment:
  actAs: [Timestampable, Signable]
  columns:
    order_id:
      type: integer
      notnull: true
    text:
      type: clob
      notnull: true
  relations:
    CommentReads:
      type: many
      local: id
      foreign: comment_id

CommentReads:
  columns:
    comment_id:
      type: integer
      notnull: true
    user_id:
      type: integer
      notnull: true
  indexes:
    unique_for_inserts:
      fields: [comment_id, user_id]
      type: unique

sfGuardUser:
  relations:
    Orders:
      class: Order
      type: many
      local: id
      foreign: created_by
      foreignAlias: Creator
    CommentReads:
      type: many
      local: id
      foreign: user_id
      foreignAlias: Reader
Invoice:
  columns:
    order_id:
      type: integer
      notnull: true
    description:
      type: string(255)
      notnull: true
    number:
      type: float
      notnull: true
    price:
      type: float
      notnull: true
    sum:
      type: float
      notnull: true    
  relations:
    Order: { local: order_id, foreign: id, onDelete: CASCADE, foreignAlias: Invoices }