Warehouse: # Склад
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
  relations:
    Users:
      class: sfGuardUser
      refClass: RefWarehouseUser
      local: warehouse_id
      foreign: user_id
      foreignAlias: Warehouses
    Inputs:
      class: MaterialMovement
      local: id
      foreign: to_id
      foreignAlias: From
      type: many
    Outputs:
      class: MaterialMovement
      local: id
      foreign: from_id
      foreignAlias: To
      type: many

RefWarehouseUser: # Ответственные за склад
  columns:
    warehouse_id:
      type: integer
      primary: true
    user_id:
      type: integer
      primary: true
  relations:
    Warehouse:
      local: warehouse_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

MaterialMovement: # Движения материалов
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    type:
      type: enum
      values:
        - arrival      # приход
        - transfer     # перемещение
        - utilization  # расход
        - writeoff     # списание
      notnull: true
    from_id:
      type: integer
    to_id:
      type: integer

    transfer_id:
      type: integer
    arrival_id:
      type: integer
    utilization_id:
      type: integer
    writeoff_id:
      type: integer
  relations:
    Transfer:
      class: MaterialMovementTransfer
      local: transfer_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Movement
    Writeoff:
      class: MaterialMovementWriteoff
      local: writeoff_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Movement
    Utilization:
      class: MaterialMovementUtilization
      local: utilization_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Movement
    Arrival:
      class: MaterialMovementArrival
      local: arrival_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Movement
    Materials:
      class: MaterialMovementMaterials
      foreignAlias: Movement
      local: id
      foreign: movement_id
      type: many

MaterialMovementMaterials: # Список материалов движения материалов
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    movement_id:
      type: integer
      notnull: true
    material_id:
      type: integer
      notnull: true
    amount:
      type: decimal
      scale: 4
      notnull: true
    price:
      type: decimal
      scale: 2
      notnull: true
  relations:
    Material:
      local: material_id
      foreign: id
      type: one

MaterialMovementTransfer: # Перемещение материалов [склад → склад]
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    name:
      type: clob

MaterialMovementWriteoff: # Перемещение материалов [склад → списано]
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    name:
      type: clob

MaterialMovementUtilization: # Перемещение материалов ]склад → использовано в продукции]
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    order_id:
      type: integer
      notnull: true
    work_id:
      type: integer
      notnull: true
  relations:
    Order:
      local: order_id
      foreign: id
      type: one
      foreignType: many
    Work:
      local: work_id
      foreign: id
      type: one
      foreignType: many

MaterialMovementArrival: # Перемещение материалов [поставщик → склад]
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    arrived_at: # дата накладной
      type: timestamp
      notnull: true
    bill: # накладная
      type: string(255)
      notnull: true
    supplier_id:
      type: integer
      notnull: true
  relations:
    Supplier:
      local: supplier_id
      foreign: id
      foreignAlias: Arrivals
