# Участок
Area:
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    slug:
      type: string(255)
      default: ""
      notnull: true
    style:
      type: clob
    rate:
      type: decimal
      scale: 2
  relations:
    Works:
      class: Work
      type: many
      local: id
      foreign: area_id
    Masters:
      class: sfGuardUser
      refClass: RefAreaUser
      local: area_id
      foreign: user_id
      foreignAlias: Areas
    Workers:
      class: sfGuardUser
      refClass: RefAreaWorker
      local: area_id
      foreign: user_id
      foreignAlias: Areas

RefAreaUser:
  columns:
    area_id:
      type: integer
      primary: true
    user_id:
      type: integer
      primary: true
  relations:
    Area:
      local: area_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

RefAreaWorker:
  columns:
    area_id:
      type: integer
      primary: true
    user_id:
      type: integer
      primary: true
  relations:
    Area:
      local: area_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

# Работа
Work:
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    area_id:
      type: integer
      notnull: true
    name:
      type: string(255)
      notnull: true

# Работы заказа
RefOrderWork:
  actAs:
    Timestampable: ~
    Signable: ~
  columns:
    order_id:
      type: integer
      notnull: true
    area_id:
      type: integer
      notnull: true
    work_id:
      type: integer
      notnull: true
    master_id:
      type: integer
      notnull: true
    comment:
      type: string(255)
    is_completed:
      type: boolean
      default: false
      notnull: true
    planned_start:
      type: timestamp
    planned_finish:
      type: timestamp
    finished_at:
      type: timestamp
  relations:
    Order:
      local: order_id
      foreign: id
    Area:
      local: area_id
      foreign: id
    Work:
      local: work_id
      foreign: id
    Master:
      local: master_id
      class: sfGuardUser
      foreign: id
      foreignAlias: Works
