# Участок
Area:
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
  relations:
    Works:
      class: Work
      type: many
      local: id
      foreign: area_id

# Работа
Work:
  actAs:
    Timestampable: ~
    Signable: ~
    SoftDelete: ~
  columns:
    area_id:
      type: integer
      notnull: true
    name:
      type: string(255)
      notnull: true
  relations:
    Orders:
      class: Order
      refClass: RefOrderWork
      local: work_id
      foreign: order_id
      foreignAlias: Works

# Работы заказа
RefOrderWork:
  actAs:
    Timestampable: ~
    Signable: ~
  columns:
    order_id:
      type: integer
      notnull: true
    work_id:
      type: integer
      notnull: true
    comment:
      type: string(255)
  relations:
    Order:
      local: order_id
      foreign: id
    Work:
      local: work_id
      foreign: id
